### ISSUE TITLE
Fonts with same name same weight and same italic

### ISSUE THREAD

**Issue by asakurato** [moi15moi/FontCollector#8]
So I have the following issue. I have a font named SF Pro Display, that has different weight (and italics) options in the same name (see attached screenshots)
![image](https://user-images.githubusercontent.com/20476454/205493008-8fc21218-6fab-45d1-9a39-4bf6ed4e1e8d.png)
![image](https://user-images.githubusercontent.com/20476454/205493025-30622e95-7c8f-45c3-9d9a-0b224ec663f4.png)
In the ass file, I'm using the first one and Aegisub font collector does collect the first one (shown below). So for some reason, this tool collects the italic variant.
![image](https://user-images.githubusercontent.com/20476454/205493707-1949abb3-4d0a-4552-ba79-09219007d7d5.png)

**Comment by moi15moi** [comment]
I talked in pm with @asakurato.

Here is the subs and the font he provided me: [Font _ Subs.zip](https://github.com/moi15moi/FontCollector/files/10148663/Font._.Subs.zip)

I will test and see what can cause this problem.

**Comment by moi15moi** [comment]
@asakurato I tried with what you provided me.

Aegisub and FontCollector returned me the same font.
This means both of them returned me the font: **SFProDisplay-BoldItalic.ttf**

**Comment by asakurato** [comment]
Well, I didn't get it from apple website (and they are .dmg files), but the files I gave you were collected by Aegisub, so truetype or not, Aegisub did it correctly. The weird thing is, Fontcollector now also collects correct the Bold variant, without changing anything else.

**Comment by asakurato** [comment]
Yeah, there's something weird going on. I tested it *again* and it have me Italic variant, *again*.

**Comment by asakurato** [comment]
While doing the tests, I found another issue, where Fontcollector collects font under different name than Aegisub, which can potentially double fonts if the output folder is not empty.

**Comment by moi15moi** [comment]
> Well, I didn't get it from apple website (and they are .dmg files)

Dmg file can be extracted and you will see that apple provided opentype font.

> but the files I gave you were collected by Aegisub, so truetype or not, Aegisub did it correctly. The weird thing is, Fontcollector now also collects correct the Bold variant, without changing anything else.

To collect the font in the system, FontCollector depend on matplotlib.
matplotlib looks into these directory: ``C:\Windows\Fonts`` and ``%userprofile%\AppData\Local\Microsoft\Windows\Fonts``.

The problem seems to be from windows.

From what I can see, I can only install one of these, because if I install one of them, the other one will be ignored:
Ex1:
1. Install SFProDisplay-Bold.ttf
2. Install SFProDisplay-BoldItalic.ttf
3. I can only see the font SFProDisplay-Bold.ttf in ``C:\Windows\Fonts``

Ex2:
1. Install SFProDisplay-BoldItalic.ttf
2. Install SFProDisplay-Bold.ttf
3. I can only see the font SFProDisplay-BoldItalic.ttf in ``C:\Windows\Fonts``

So, could you check if you see the file ``SFProDisplay-Bold.ttf`` and ``SFProDisplay-BoldItalic.ttf``?

> While doing the tests, I found another issue, where Fontcollector collects font under different name than Aegisub, which can potentially double fonts if the output folder is not empty.

This is not an issue.

**Comment by asakurato** [comment]
Italic variant doesn't show up in C:\Windows\Fonts, but when I try to install it, it says it's already installed. And even if I install it, it still doesn't show up there. But it's being collected from *somewhere*, rigth?

**Comment by moi15moi** [comment]
I did some research about your font.

### Why it happen?
- The [OS/2 table](https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fsselection) say that the font "SF Pro Display Italic" isn't italic.
- The [macstyle in the head](https://learn.microsoft.com/en-us/typography/opentype/spec/head) doesn't say that it is italic.

Because of that, FontCollector think that both font are exactly the same. That's why it doesn't always return the same font.

### Is there a way to solve this problem?
Even libass/vsfilter doesn't know that the font is italic.

Even Aegisub FontCollector doesn't always return the same font.
For example, if you install ``SFProDisplay-BoldItalic.ttf`` then ``SFProDisplay-Bold.ttf``, aegisub will return you ``SFProDisplay-BoldItalic.ttf``
But, if you install ``SFProDisplay-Bold.ttf`` then ``SFProDisplay-BoldItalic.ttf``, aegisub will return you ``SFProDisplay-Bold.ttf``

In brief, the font is so broken that for now, I can't see a way to find a solution.

**Comment by moi15moi** [comment]
I did more research about your fonts.
There is no direct way to know if VSFilter display ``SFProDisplay-Bold - Original.ttf`` or ``SFProDisplay-BoldItalic - Original.ttf``
So, I created ``SFProDisplay-BoldItalic - Generated.ttf`` which is the same has ``SFProDisplay-BoldItalic - Original.ttf``, but the char "A" is mapped to the glyph "B".
Here is my [Test.zip](https://github.com/moi15moi/FontCollector/files/12859910/Test.zip)

Install ``SFProDisplay-BoldItalic - Generated.ttf`` before ``SFProDisplay-Bold - Original.ttf`` (VSFilter)
![image](https://github.com/moi15moi/FontCollector/assets/80980684/ae6d5af4-c411-416d-95e2-a1ad570f518e)

Install ``SFProDisplay-Bold - Original.ttf`` before ``SFProDisplay-BoldItalic - Generated.ttf`` (VSFilter)
![image](https://github.com/moi15moi/FontCollector/assets/80980684/5061af2f-4853-4194-bfcf-8db98c28a331)

GDI doesn't recognize the font ``SFProDisplay-BoldItalic - Original.ttf`` as italic.
However, DirectWrite recognizes it as italic because the NameRecord nameid 17 is set to "Bold Italic" (which appears to match the explanation [here](https://www.noesisengine.com/bugs/file_download.php?file_id=1356&type=bug#:~:text=2.-,Font%20matching%20process,%2C%20FontStretch%2C%20and%20FontStyle%20respectively))

However, our goal is to match GDI.
In brief, if two fonts have exactly the same score (the score is generated like [this](https://github.com/moi15moi/FontCollector/blob/5b51507e5e3ddae66160087dbc130c4cf96a0ece/font_collector/font/abc_font.py#L240)), we prioritize the older font over the newest one.

This feature will be available in FontCollector 3.0.0

**Comment by astiob** [comment]
Not the first time Apple does this: https://github.com/libass/libass/issues/525. If you can, do please verify this on the latest macOS and file a report with Apple. (If not, oh well.)
